//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkinSelfieDB : DbContext
    {
        public SkinSelfieDB()
            : base("name=SkinSelfieDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyPart> BodyParts { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<SkinRegion> SkinRegions { get; set; }
        public virtual DbSet<UserCondition> UserConditions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Study> Studies { get; set; }
        public virtual DbSet<StudyEnrolment> StudyEnrolments { get; set; }
    }
}
