//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Treatment { get; set; }
        public string Notes { get; set; }
        public string PhotoDescription { get; set; }
        public Nullable<int> Rating { get; set; }
        public int UserConditionId { get; set; }
        public string ThumbUrl { get; set; }
    
        public virtual UserCondition UserCondition { get; set; }
    }
}
