//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int OwnerId { get; set; }
        public string SharedEmail { get; set; }
        public int ConditionId { get; set; }
        public bool Updated { get; set; }
    
        public virtual UserCondition UserCondition { get; set; }
        public virtual User Owner { get; set; }
    }
}
