//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkinRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkinRegion()
        {
            this.UserConditions = new HashSet<UserCondition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BodyPartId { get; set; }
    
        public virtual BodyPart BodyPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCondition> UserConditions { get; set; }
    }
}
