//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyEnrolment
    {
        public int Id { get; set; }
        public int StudyId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Enrolled { get; set; }
    
        public virtual Study Study { get; set; }
        public virtual User User { get; set; }
    }
}
