//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserCondition()
        {
            this.Photos = new HashSet<Photo>();
            this.Shares = new HashSet<Share>();
        }
    
        public int Id { get; set; }
        public int SkinRegionId { get; set; }
        public int OwnerId { get; set; }
        public string Treatment { get; set; }
        public string Condition { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> Passcode { get; set; }
        public bool Finished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Shares { get; set; }
        public virtual SkinRegion SkinRegion { get; set; }
        public virtual User Owner { get; set; }
    }
}
