//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinSelfie {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SkinSelfie.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Camera_adjustOverlay {
            get {
                return ResourceManager.GetString("Camera_adjustOverlay", resourceCulture);
            }
        }
        
        public static string Camera_hideSlider {
            get {
                return ResourceManager.GetString("Camera_hideSlider", resourceCulture);
            }
        }
        
        public static string Camera_permissionReq {
            get {
                return ResourceManager.GetString("Camera_permissionReq", resourceCulture);
            }
        }
        
        public static string Camera_tip1_message {
            get {
                return ResourceManager.GetString("Camera_tip1_message", resourceCulture);
            }
        }
        
        public static string Camera_tip1_title {
            get {
                return ResourceManager.GetString("Camera_tip1_title", resourceCulture);
            }
        }
        
        public static string Camera_tip2_message {
            get {
                return ResourceManager.GetString("Camera_tip2_message", resourceCulture);
            }
        }
        
        public static string Camera_tip2_title {
            get {
                return ResourceManager.GetString("Camera_tip2_title", resourceCulture);
            }
        }
        
        public static string Camera_title {
            get {
                return ResourceManager.GetString("Camera_title", resourceCulture);
            }
        }
        
        public static string ChangePass_confirmPass {
            get {
                return ResourceManager.GetString("ChangePass_confirmPass", resourceCulture);
            }
        }
        
        public static string ChangePass_confirmPassTemp {
            get {
                return ResourceManager.GetString("ChangePass_confirmPassTemp", resourceCulture);
            }
        }
        
        public static string ChangePass_currentPass {
            get {
                return ResourceManager.GetString("ChangePass_currentPass", resourceCulture);
            }
        }
        
        public static string ChangePass_currentPassTemp {
            get {
                return ResourceManager.GetString("ChangePass_currentPassTemp", resourceCulture);
            }
        }
        
        public static string ChangePass_error {
            get {
                return ResourceManager.GetString("ChangePass_error", resourceCulture);
            }
        }
        
        public static string ChangePass_newPass {
            get {
                return ResourceManager.GetString("ChangePass_newPass", resourceCulture);
            }
        }
        
        public static string ChangePass_newPassTemp {
            get {
                return ResourceManager.GetString("ChangePass_newPassTemp", resourceCulture);
            }
        }
        
        public static string ChangePass_successMessage {
            get {
                return ResourceManager.GetString("ChangePass_successMessage", resourceCulture);
            }
        }
        
        public static string ChangePass_successTitle {
            get {
                return ResourceManager.GetString("ChangePass_successTitle", resourceCulture);
            }
        }
        
        public static string ChangePass_title {
            get {
                return ResourceManager.GetString("ChangePass_title", resourceCulture);
            }
        }
        
        public static string ConditionEdit_blurbEdit {
            get {
                return ResourceManager.GetString("ConditionEdit_blurbEdit", resourceCulture);
            }
        }
        
        public static string ConditionEdit_blurbNew {
            get {
                return ResourceManager.GetString("ConditionEdit_blurbNew", resourceCulture);
            }
        }
        
        public static string ConditionEdit_bodyPart {
            get {
                return ResourceManager.GetString("ConditionEdit_bodyPart", resourceCulture);
            }
        }
        
        public static string ConditionEdit_bodyPartHead {
            get {
                return ResourceManager.GetString("ConditionEdit_bodyPartHead", resourceCulture);
            }
        }
        
        public static string ConditionEdit_conditionName {
            get {
                return ResourceManager.GetString("ConditionEdit_conditionName", resourceCulture);
            }
        }
        
        public static string ConditionEdit_conditionNameError {
            get {
                return ResourceManager.GetString("ConditionEdit_conditionNameError", resourceCulture);
            }
        }
        
        public static string ConditionEdit_conditionNameHead {
            get {
                return ResourceManager.GetString("ConditionEdit_conditionNameHead", resourceCulture);
            }
        }
        
        public static string ConditionEdit_confirm {
            get {
                return ResourceManager.GetString("ConditionEdit_confirm", resourceCulture);
            }
        }
        
        public static string ConditionEdit_confirmTitle {
            get {
                return ResourceManager.GetString("ConditionEdit_confirmTitle", resourceCulture);
            }
        }
        
        public static string ConditionEdit_delete {
            get {
                return ResourceManager.GetString("ConditionEdit_delete", resourceCulture);
            }
        }
        
        public static string ConditionEdit_deleteError {
            get {
                return ResourceManager.GetString("ConditionEdit_deleteError", resourceCulture);
            }
        }
        
        public static string ConditionEdit_deleteSuccessMessage {
            get {
                return ResourceManager.GetString("ConditionEdit_deleteSuccessMessage", resourceCulture);
            }
        }
        
        public static string ConditionEdit_deleteSuccessTitle {
            get {
                return ResourceManager.GetString("ConditionEdit_deleteSuccessTitle", resourceCulture);
            }
        }
        
        public static string ConditionEdit_deleteWarningMessage {
            get {
                return ResourceManager.GetString("ConditionEdit_deleteWarningMessage", resourceCulture);
            }
        }
        
        public static string ConditionEdit_deleteWarningTitle {
            get {
                return ResourceManager.GetString("ConditionEdit_deleteWarningTitle", resourceCulture);
            }
        }
        
        public static string ConditionEdit_finished {
            get {
                return ResourceManager.GetString("ConditionEdit_finished", resourceCulture);
            }
        }
        
        public static string ConditionEdit_markFinished {
            get {
                return ResourceManager.GetString("ConditionEdit_markFinished", resourceCulture);
            }
        }
        
        public static string ConditionEdit_passcode {
            get {
                return ResourceManager.GetString("ConditionEdit_passcode", resourceCulture);
            }
        }
        
        public static string ConditionEdit_reminderEnabled {
            get {
                return ResourceManager.GetString("ConditionEdit_reminderEnabled", resourceCulture);
            }
        }
        
        public static string ConditionEdit_reminderFreq {
            get {
                return ResourceManager.GetString("ConditionEdit_reminderFreq", resourceCulture);
            }
        }
        
        public static string ConditionEdit_skinRegion {
            get {
                return ResourceManager.GetString("ConditionEdit_skinRegion", resourceCulture);
            }
        }
        
        public static string ConditionEdit_skinRegionHead {
            get {
                return ResourceManager.GetString("ConditionEdit_skinRegionHead", resourceCulture);
            }
        }
        
        public static string ConditionEdit_startDate {
            get {
                return ResourceManager.GetString("ConditionEdit_startDate", resourceCulture);
            }
        }
        
        public static string ConditionEdit_submitError {
            get {
                return ResourceManager.GetString("ConditionEdit_submitError", resourceCulture);
            }
        }
        
        public static string ConditionEdit_titleEdit {
            get {
                return ResourceManager.GetString("ConditionEdit_titleEdit", resourceCulture);
            }
        }
        
        public static string ConditionEdit_titleNew {
            get {
                return ResourceManager.GetString("ConditionEdit_titleNew", resourceCulture);
            }
        }
        
        public static string ConditionEdit_updateError {
            get {
                return ResourceManager.GetString("ConditionEdit_updateError", resourceCulture);
            }
        }
        
        public static string ConditionEdit_updateSuccess {
            get {
                return ResourceManager.GetString("ConditionEdit_updateSuccess", resourceCulture);
            }
        }
        
        public static string CreateAcc_btn_submit {
            get {
                return ResourceManager.GetString("CreateAcc_btn_submit", resourceCulture);
            }
        }
        
        public static string CreateAcc_btn_privacy {
            get {
                return ResourceManager.GetString("CreateAcc_btn_privacy", resourceCulture);
            }
        }
        
        public static string CreateAcc_btn_terms {
            get {
                return ResourceManager.GetString("CreateAcc_btn_terms", resourceCulture);
            }
        }
        
        public static string CreateAcc_termsPrivacyCheck {
            get {
                return ResourceManager.GetString("CreateAcc_termsPrivacyCheck", resourceCulture);
            }
        }
        
        public static string CreateAcc_termsPrivacyFail {
            get {
                return ResourceManager.GetString("CreateAcc_termsPrivacyFail", resourceCulture);
            }
        }
        
        public static string CreateAcc_confirmMessage {
            get {
                return ResourceManager.GetString("CreateAcc_confirmMessage", resourceCulture);
            }
        }
        
        public static string CreateAcc_confirmTitle {
            get {
                return ResourceManager.GetString("CreateAcc_confirmTitle", resourceCulture);
            }
        }
        
        public static string CreateAcc_dob {
            get {
                return ResourceManager.GetString("CreateAcc_dob", resourceCulture);
            }
        }
        
        public static string CreateAcc_email {
            get {
                return ResourceManager.GetString("CreateAcc_email", resourceCulture);
            }
        }
        
        public static string CreateAcc_emailTemp {
            get {
                return ResourceManager.GetString("CreateAcc_emailTemp", resourceCulture);
            }
        }
        
        public static string CreateAcc_errorTitle {
            get {
                return ResourceManager.GetString("CreateAcc_errorTitle", resourceCulture);
            }
        }
        
        public static string CreateAcc_name {
            get {
                return ResourceManager.GetString("CreateAcc_name", resourceCulture);
            }
        }
        
        public static string CreateAcc_nameTemp {
            get {
                return ResourceManager.GetString("CreateAcc_nameTemp", resourceCulture);
            }
        }
        
        public static string CreateAcc_password {
            get {
                return ResourceManager.GetString("CreateAcc_password", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordConfirm {
            get {
                return ResourceManager.GetString("CreateAcc_passwordConfirm", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordMismatchMessage {
            get {
                return ResourceManager.GetString("CreateAcc_passwordMismatchMessage", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordMismatchTitle {
            get {
                return ResourceManager.GetString("CreateAcc_passwordMismatchTitle", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordEmpty {
            get {
                return ResourceManager.GetString("CreateAcc_passwordEmpty", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordEmptyTitle {
            get {
                return ResourceManager.GetString("CreateAcc_passwordEmptyTitle", resourceCulture);
            }
        }
        
        public static string CreateAcc_passwordTemp {
            get {
                return ResourceManager.GetString("CreateAcc_passwordTemp", resourceCulture);
            }
        }
        
        public static string CreateAcc_successMessage {
            get {
                return ResourceManager.GetString("CreateAcc_successMessage", resourceCulture);
            }
        }
        
        public static string CreateAcc_successTitle {
            get {
                return ResourceManager.GetString("CreateAcc_successTitle", resourceCulture);
            }
        }
        
        public static string CreateAcc_title {
            get {
                return ResourceManager.GetString("CreateAcc_title", resourceCulture);
            }
        }
        
        public static string Dialog_agree {
            get {
                return ResourceManager.GetString("Dialog_agree", resourceCulture);
            }
        }
        
        public static string Dialog_cancel {
            get {
                return ResourceManager.GetString("Dialog_cancel", resourceCulture);
            }
        }
        
        public static string Dialog_cancelled {
            get {
                return ResourceManager.GetString("Dialog_cancelled", resourceCulture);
            }
        }
        
        public static string Dialog_confirm {
            get {
                return ResourceManager.GetString("Dialog_confirm", resourceCulture);
            }
        }
        
        public static string Dialog_delete {
            get {
                return ResourceManager.GetString("Dialog_delete", resourceCulture);
            }
        }
        
        public static string Dialog_error {
            get {
                return ResourceManager.GetString("Dialog_error", resourceCulture);
            }
        }
        
        public static string Dialog_loading {
            get {
                return ResourceManager.GetString("Dialog_loading", resourceCulture);
            }
        }
        
        public static string Dialog_success {
            get {
                return ResourceManager.GetString("Dialog_success", resourceCulture);
            }
        }
        
        public static string Dialog_understand {
            get {
                return ResourceManager.GetString("Dialog_understand", resourceCulture);
            }
        }
        
        public static string Disclaimer_appIntent {
            get {
                return ResourceManager.GetString("Disclaimer_appIntent", resourceCulture);
            }
        }
        
        public static string Disclaimer_btn_agree {
            get {
                return ResourceManager.GetString("Disclaimer_btn_agree", resourceCulture);
            }
        }
        
        public static string Disclaimer_imageControl {
            get {
                return ResourceManager.GetString("Disclaimer_imageControl", resourceCulture);
            }
        }
        
        public static string Disclaimer_notTreatment {
            get {
                return ResourceManager.GetString("Disclaimer_notTreatment", resourceCulture);
            }
        }
        
        public static string Disclaimer_thanks {
            get {
                return ResourceManager.GetString("Disclaimer_thanks", resourceCulture);
            }
        }
        
        public static string Error_connection {
            get {
                return ResourceManager.GetString("Error_connection", resourceCulture);
            }
        }
        
        public static string Error_delete {
            get {
                return ResourceManager.GetString("Error_delete", resourceCulture);
            }
        }
        
        public static string Error_update {
            get {
                return ResourceManager.GetString("Error_update", resourceCulture);
            }
        }
        
        public static string Gallery_compareCount {
            get {
                return ResourceManager.GetString("Gallery_compareCount", resourceCulture);
            }
        }
        
        public static string Gallery_compareTooFewMessage {
            get {
                return ResourceManager.GetString("Gallery_compareTooFewMessage", resourceCulture);
            }
        }
        
        public static string Gallery_compareTooFewTitle {
            get {
                return ResourceManager.GetString("Gallery_compareTooFewTitle", resourceCulture);
            }
        }
        
        public static string Gallery_compareTooManyMessage {
            get {
                return ResourceManager.GetString("Gallery_compareTooManyMessage", resourceCulture);
            }
        }
        
        public static string Gallery_compareTooManyTitle {
            get {
                return ResourceManager.GetString("Gallery_compareTooManyTitle", resourceCulture);
            }
        }
        
        public static string Gallery_edit {
            get {
                return ResourceManager.GetString("Gallery_edit", resourceCulture);
            }
        }
        
        public static string Gallery_noPasscode {
            get {
                return ResourceManager.GetString("Gallery_noPasscode", resourceCulture);
            }
        }
        
        public static string Gallery_selected {
            get {
                return ResourceManager.GetString("Gallery_selected", resourceCulture);
            }
        }
        
        public static string Gallery_takeNew {
            get {
                return ResourceManager.GetString("Gallery_takeNew", resourceCulture);
            }
        }
        
        public static string Gallery_welcome1 {
            get {
                return ResourceManager.GetString("Gallery_welcome1", resourceCulture);
            }
        }
        
        public static string Gallery_welcome2 {
            get {
                return ResourceManager.GetString("Gallery_welcome2", resourceCulture);
            }
        }
        
        public static string Gallery_welcome3 {
            get {
                return ResourceManager.GetString("Gallery_welcome3", resourceCulture);
            }
        }
        
        public static string Login_btn_login {
            get {
                return ResourceManager.GetString("Login_btn_login", resourceCulture);
            }
        }
        
        public static string Login_error {
            get {
                return ResourceManager.GetString("Login_error", resourceCulture);
            }
        }
        
        public static string Login_errorNoEmail {
            get {
                return ResourceManager.GetString("Login_errorNoEmail", resourceCulture);
            }
        }
        
        public static string Login_title {
            get {
                return ResourceManager.GetString("Login_title", resourceCulture);
            }
        }
        
        public static string Main_activeCollections {
            get {
                return ResourceManager.GetString("Main_activeCollections", resourceCulture);
            }
        }
        
        public static string Main_add {
            get {
                return ResourceManager.GetString("Main_add", resourceCulture);
            }
        }
        
        public static string Main_authErr {
            get {
                return ResourceManager.GetString("Main_authErr", resourceCulture);
            }
        }
        
        public static string Main_connectionErr {
            get {
                return ResourceManager.GetString("Main_connectionErr", resourceCulture);
            }
        }
        
        public static string Main_feedbackMessage {
            get {
                return ResourceManager.GetString("Main_feedbackMessage", resourceCulture);
            }
        }
        
        public static string Main_feedbackOk {
            get {
                return ResourceManager.GetString("Main_feedbackOk", resourceCulture);
            }
        }
        
        public static string Main_feedbackTitle {
            get {
                return ResourceManager.GetString("Main_feedbackTitle", resourceCulture);
            }
        }
        
        public static string Main_finishedCollections {
            get {
                return ResourceManager.GetString("Main_finishedCollections", resourceCulture);
            }
        }
        
        public static string Main_loadingAppData {
            get {
                return ResourceManager.GetString("Main_loadingAppData", resourceCulture);
            }
        }
        
        public static string Main_loadingUserContent {
            get {
                return ResourceManager.GetString("Main_loadingUserContent", resourceCulture);
            }
        }
        
        public static string Main_settings {
            get {
                return ResourceManager.GetString("Main_settings", resourceCulture);
            }
        }
        
        public static string Main_title {
            get {
                return ResourceManager.GetString("Main_title", resourceCulture);
            }
        }
        
        public static string Main_welcome1 {
            get {
                return ResourceManager.GetString("Main_welcome1", resourceCulture);
            }
        }
        
        public static string Main_welcome2 {
            get {
                return ResourceManager.GetString("Main_welcome2", resourceCulture);
            }
        }
        
        public static string Main_welcome3 {
            get {
                return ResourceManager.GetString("Main_welcome3", resourceCulture);
            }
        }
        
        public static string Main_welcome4 {
            get {
                return ResourceManager.GetString("Main_welcome4", resourceCulture);
            }
        }
        
        public static string PhotoCarousel_Edit {
            get {
                return ResourceManager.GetString("PhotoCarousel_Edit", resourceCulture);
            }
        }
        
        public static string PhotoCompare_title {
            get {
                return ResourceManager.GetString("PhotoCompare_title", resourceCulture);
            }
        }
        
        public static string PhotoEdit_delete {
            get {
                return ResourceManager.GetString("PhotoEdit_delete", resourceCulture);
            }
        }
        
        public static string PhotoEdit_deleteConfirmMessage {
            get {
                return ResourceManager.GetString("PhotoEdit_deleteConfirmMessage", resourceCulture);
            }
        }
        
        public static string PhotoEdit_deleteConfirmTitle {
            get {
                return ResourceManager.GetString("PhotoEdit_deleteConfirmTitle", resourceCulture);
            }
        }
        
        public static string PhotoEdit_deleteConfirmYes {
            get {
                return ResourceManager.GetString("PhotoEdit_deleteConfirmYes", resourceCulture);
            }
        }
        
        public static string PhotoEdit_deleteErr {
            get {
                return ResourceManager.GetString("PhotoEdit_deleteErr", resourceCulture);
            }
        }
        
        public static string PhotoEdit_deleteSuccess {
            get {
                return ResourceManager.GetString("PhotoEdit_deleteSuccess", resourceCulture);
            }
        }
        
        public static string PhotoEdit_finished {
            get {
                return ResourceManager.GetString("PhotoEdit_finished", resourceCulture);
            }
        }
        
        public static string PhotoEdit_notes {
            get {
                return ResourceManager.GetString("PhotoEdit_notes", resourceCulture);
            }
        }
        
        public static string PhotoEdit_shotConditions {
            get {
                return ResourceManager.GetString("PhotoEdit_shotConditions", resourceCulture);
            }
        }
        
        public static string PhotoEdit_treatment {
            get {
                return ResourceManager.GetString("PhotoEdit_treatment", resourceCulture);
            }
        }
        
        public static string PhotoEdit_updateErr {
            get {
                return ResourceManager.GetString("PhotoEdit_updateErr", resourceCulture);
            }
        }
        
        public static string PhotoEdit_updateSuccess {
            get {
                return ResourceManager.GetString("PhotoEdit_updateSuccess", resourceCulture);
            }
        }
        
        public static string PhotoEdit_uploadErr {
            get {
                return ResourceManager.GetString("PhotoEdit_uploadErr", resourceCulture);
            }
        }
        
        public static string PhotoEdit_uploadSuccess {
            get {
                return ResourceManager.GetString("PhotoEdit_uploadSuccess", resourceCulture);
            }
        }
        
        public static string ResetPassword_failure {
            get {
                return ResourceManager.GetString("ResetPassword_failure", resourceCulture);
            }
        }
        
        public static string ResetPassword_message {
            get {
                return ResourceManager.GetString("ResetPassword_message", resourceCulture);
            }
        }
        
        public static string ResetPassword_success {
            get {
                return ResourceManager.GetString("ResetPassword_success", resourceCulture);
            }
        }
        
        public static string ResetPassword_title {
            get {
                return ResourceManager.GetString("ResetPassword_title", resourceCulture);
            }
        }
        
        public static string Settings_accountHeader {
            get {
                return ResourceManager.GetString("Settings_accountHeader", resourceCulture);
            }
        }
        
        public static string Settings_addPIN {
            get {
                return ResourceManager.GetString("Settings_addPIN", resourceCulture);
            }
        }
        
        public static string Settings_addPINEnter {
            get {
                return ResourceManager.GetString("Settings_addPINEnter", resourceCulture);
            }
        }
        
        public static string Settings_addPINSuccess {
            get {
                return ResourceManager.GetString("Settings_addPINSuccess", resourceCulture);
            }
        }
        
        public static string Settings_appHeader {
            get {
                return ResourceManager.GetString("Settings_appHeader", resourceCulture);
            }
        }
        
        public static string Settings_changePassword {
            get {
                return ResourceManager.GetString("Settings_changePassword", resourceCulture);
            }
        }
        
        public static string Settings_changePIN {
            get {
                return ResourceManager.GetString("Settings_changePIN", resourceCulture);
            }
        }
        
        public static string Settings_dangerHeader {
            get {
                return ResourceManager.GetString("Settings_dangerHeader", resourceCulture);
            }
        }
        
        public static string Settings_deleteAcc {
            get {
                return ResourceManager.GetString("Settings_deleteAcc", resourceCulture);
            }
        }
        
        public static string Settings_deleteAccFailure {
            get {
                return ResourceManager.GetString("Settings_deleteAccFailure", resourceCulture);
            }
        }
        
        public static string Settings_deleteAccSafeWord {
            get {
                return ResourceManager.GetString("Settings_deleteAccSafeWord", resourceCulture);
            }
        }
        
        public static string Settings_deleteAccSafeWordMismatch {
            get {
                return ResourceManager.GetString("Settings_deleteAccSafeWordMismatch", resourceCulture);
            }
        }
        
        public static string Settings_deleteAccSuccess {
            get {
                return ResourceManager.GetString("Settings_deleteAccSuccess", resourceCulture);
            }
        }
        
        public static string Settings_deleteAccWarning {
            get {
                return ResourceManager.GetString("Settings_deleteAccWarning", resourceCulture);
            }
        }
        
        public static string Settings_logOut {
            get {
                return ResourceManager.GetString("Settings_logOut", resourceCulture);
            }
        }
        
        public static string Settings_logOutConfirm {
            get {
                return ResourceManager.GetString("Settings_logOutConfirm", resourceCulture);
            }
        }
        
        public static string Settings_logoutConfirmTitle {
            get {
                return ResourceManager.GetString("Settings_logoutConfirmTitle", resourceCulture);
            }
        }
        
        public static string Settings_removePIN {
            get {
                return ResourceManager.GetString("Settings_removePIN", resourceCulture);
            }
        }
        
        public static string Settings_removePINEnter {
            get {
                return ResourceManager.GetString("Settings_removePINEnter", resourceCulture);
            }
        }
        
        public static string Settings_removePINSuccess {
            get {
                return ResourceManager.GetString("Settings_removePINSuccess", resourceCulture);
            }
        }
        
        public static string Settings_resendEmail {
            get {
                return ResourceManager.GetString("Settings_resendEmail", resourceCulture);
            }
        }
        
        public static string Settings_resendEmailFail {
            get {
                return ResourceManager.GetString("Settings_resendEmailFail", resourceCulture);
            }
        }
        
        public static string Settings_resendEmailSuccess {
            get {
                return ResourceManager.GetString("Settings_resendEmailSuccess", resourceCulture);
            }
        }
        
        public static string Settings_resetPassword {
            get {
                return ResourceManager.GetString("Settings_resetPassword", resourceCulture);
            }
        }
        
        public static string Settings_resetPasswordFailure {
            get {
                return ResourceManager.GetString("Settings_resetPasswordFailure", resourceCulture);
            }
        }
        
        public static string Settings_resetPasswordSuccess {
            get {
                return ResourceManager.GetString("Settings_resetPasswordSuccess", resourceCulture);
            }
        }
        
        public static string Settings_resetPasswordWarning {
            get {
                return ResourceManager.GetString("Settings_resetPasswordWarning", resourceCulture);
            }
        }
        
        public static string Settings_title {
            get {
                return ResourceManager.GetString("Settings_title", resourceCulture);
            }
        }
        
        public static string Settings_warning {
            get {
                return ResourceManager.GetString("Settings_warning", resourceCulture);
            }
        }
        
        public static string Unlock_blurbNew {
            get {
                return ResourceManager.GetString("Unlock_blurbNew", resourceCulture);
            }
        }
        
        public static string Unlock_blurbUnlock {
            get {
                return ResourceManager.GetString("Unlock_blurbUnlock", resourceCulture);
            }
        }
        
        public static string Unlock_btnForgot {
            get {
                return ResourceManager.GetString("Unlock_btnForgot", resourceCulture);
            }
        }
        
        public static string Unlock_btnNew {
            get {
                return ResourceManager.GetString("Unlock_btnNew", resourceCulture);
            }
        }
        
        public static string Unlock_btnUnlock {
            get {
                return ResourceManager.GetString("Unlock_btnUnlock", resourceCulture);
            }
        }
        
        public static string Unlock_confirm {
            get {
                return ResourceManager.GetString("Unlock_confirm", resourceCulture);
            }
        }
        
        public static string Unlock_confirmErr {
            get {
                return ResourceManager.GetString("Unlock_confirmErr", resourceCulture);
            }
        }
        
        public static string Unlock_folderForgotMessage {
            get {
                return ResourceManager.GetString("Unlock_folderForgotMessage", resourceCulture);
            }
        }
        
        public static string Unlock_folderForgotOk {
            get {
                return ResourceManager.GetString("Unlock_folderForgotOk", resourceCulture);
            }
        }
        
        public static string Unlock_folderResetSuccess {
            get {
                return ResourceManager.GetString("Unlock_folderResetSuccess", resourceCulture);
            }
        }
        
        public static string Unlock_forgotConfirm {
            get {
                return ResourceManager.GetString("Unlock_forgotConfirm", resourceCulture);
            }
        }
        
        public static string Unlock_forgotMessage {
            get {
                return ResourceManager.GetString("Unlock_forgotMessage", resourceCulture);
            }
        }
        
        public static string Unlock_forgotTitle {
            get {
                return ResourceManager.GetString("Unlock_forgotTitle", resourceCulture);
            }
        }
        
        public static string Unlock_mismatch {
            get {
                return ResourceManager.GetString("Unlock_mismatch", resourceCulture);
            }
        }
        
        public static string Unlock_ohwtf {
            get {
                return ResourceManager.GetString("Unlock_ohwtf", resourceCulture);
            }
        }
        
        public static string Unlock_resetErr {
            get {
                return ResourceManager.GetString("Unlock_resetErr", resourceCulture);
            }
        }
        
        public static string Unlock_titleNew {
            get {
                return ResourceManager.GetString("Unlock_titleNew", resourceCulture);
            }
        }
        
        public static string Unlock_titleUnlock {
            get {
                return ResourceManager.GetString("Unlock_titleUnlock", resourceCulture);
            }
        }
        
        public static string Welcome_blurb {
            get {
                return ResourceManager.GetString("Welcome_blurb", resourceCulture);
            }
        }
        
        public static string Welcome_btn_createAcc {
            get {
                return ResourceManager.GetString("Welcome_btn_createAcc", resourceCulture);
            }
        }
        
        public static string Welcome_btn_forgottenPassword {
            get {
                return ResourceManager.GetString("Welcome_btn_forgottenPassword", resourceCulture);
            }
        }
        
        public static string Welcome_btn_signIn {
            get {
                return ResourceManager.GetString("Welcome_btn_signIn", resourceCulture);
            }
        }
        
        public static string Welcome_header {
            get {
                return ResourceManager.GetString("Welcome_header", resourceCulture);
            }
        }
        
        public static string Welcome_title {
            get {
                return ResourceManager.GetString("Welcome_title", resourceCulture);
            }
        }
        
        public static string App_loginError {
            get {
                return ResourceManager.GetString("App_loginError", resourceCulture);
            }
        }
        
        public static string App_passwordFailMessage {
            get {
                return ResourceManager.GetString("App_passwordFailMessage", resourceCulture);
            }
        }
        
        public static string App_passwordFailTitle {
            get {
                return ResourceManager.GetString("App_passwordFailTitle", resourceCulture);
            }
        }
        
        public static string App_pinPromptMessage {
            get {
                return ResourceManager.GetString("App_pinPromptMessage", resourceCulture);
            }
        }
        
        public static string App_pinPromptNo {
            get {
                return ResourceManager.GetString("App_pinPromptNo", resourceCulture);
            }
        }
        
        public static string App_pinPromptTitle {
            get {
                return ResourceManager.GetString("App_pinPromptTitle", resourceCulture);
            }
        }
        
        public static string App_pinPromptYes {
            get {
                return ResourceManager.GetString("App_pinPromptYes", resourceCulture);
            }
        }
        
        public static string Main_shareComingSoon {
            get {
                return ResourceManager.GetString("Main_shareComingSoon", resourceCulture);
            }
        }
        
        public static string Help_controlBody {
            get {
                return ResourceManager.GetString("Help_controlBody", resourceCulture);
            }
        }
        
        public static string Help_controlHeading {
            get {
                return ResourceManager.GetString("Help_controlHeading", resourceCulture);
            }
        }
        
        public static string Help_funcBody {
            get {
                return ResourceManager.GetString("Help_funcBody", resourceCulture);
            }
        }
        
        public static string Help_funcHeading {
            get {
                return ResourceManager.GetString("Help_funcHeading", resourceCulture);
            }
        }
        
        public static string Help_heading {
            get {
                return ResourceManager.GetString("Help_heading", resourceCulture);
            }
        }
        
        public static string Help_securityBody {
            get {
                return ResourceManager.GetString("Help_securityBody", resourceCulture);
            }
        }
        
        public static string Help_securityHeading {
            get {
                return ResourceManager.GetString("Help_securityHeading", resourceCulture);
            }
        }
        
        public static string Help_shareBody {
            get {
                return ResourceManager.GetString("Help_shareBody", resourceCulture);
            }
        }
        
        public static string Help_shareHeading {
            get {
                return ResourceManager.GetString("Help_shareHeading", resourceCulture);
            }
        }
        
        public static string Help_title {
            get {
                return ResourceManager.GetString("Help_title", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_title", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_intro {
            get {
                return ResourceManager.GetString("PrivacyPolicy_intro", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_KeyPointsTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicy_KeyPointsTitle", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_KeyPoints {
            get {
                return ResourceManager.GetString("PrivacyPolicy_KeyPoints", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_Full {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Full", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy_FullTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicy_FullTitle", resourceCulture);
            }
        }
        
        public static string Terms_Title {
            get {
                return ResourceManager.GetString("Terms_Title", resourceCulture);
            }
        }
        
        public static string Terms_Intro {
            get {
                return ResourceManager.GetString("Terms_Intro", resourceCulture);
            }
        }
        
        public static string Terms_UseTitle {
            get {
                return ResourceManager.GetString("Terms_UseTitle", resourceCulture);
            }
        }
        
        public static string Terms_UseBody {
            get {
                return ResourceManager.GetString("Terms_UseBody", resourceCulture);
            }
        }
        
        public static string Terms_ProhibitedTitle {
            get {
                return ResourceManager.GetString("Terms_ProhibitedTitle", resourceCulture);
            }
        }
        
        public static string Terms_ProhibitedBody {
            get {
                return ResourceManager.GetString("Terms_ProhibitedBody", resourceCulture);
            }
        }
        
        public static string Terms_ContentTitle {
            get {
                return ResourceManager.GetString("Terms_ContentTitle", resourceCulture);
            }
        }
        
        public static string Terms_ContentBody {
            get {
                return ResourceManager.GetString("Terms_ContentBody", resourceCulture);
            }
        }
        
        public static string Terms_BehaviourTitle {
            get {
                return ResourceManager.GetString("Terms_BehaviourTitle", resourceCulture);
            }
        }
        
        public static string Terms_BehaviourBody {
            get {
                return ResourceManager.GetString("Terms_BehaviourBody", resourceCulture);
            }
        }
        
        public static string Terms_MonitoringTitle {
            get {
                return ResourceManager.GetString("Terms_MonitoringTitle", resourceCulture);
            }
        }
        
        public static string Terms_MonitoringBody {
            get {
                return ResourceManager.GetString("Terms_MonitoringBody", resourceCulture);
            }
        }
        
        public static string Terms_TerminationTitle {
            get {
                return ResourceManager.GetString("Terms_TerminationTitle", resourceCulture);
            }
        }
        
        public static string Terms_TerminationBody {
            get {
                return ResourceManager.GetString("Terms_TerminationBody", resourceCulture);
            }
        }
        
        public static string Terms_LinksTitle {
            get {
                return ResourceManager.GetString("Terms_LinksTitle", resourceCulture);
            }
        }
        
        public static string Terms_LinksBody {
            get {
                return ResourceManager.GetString("Terms_LinksBody", resourceCulture);
            }
        }
        
        public static string Terms_RightsTitle {
            get {
                return ResourceManager.GetString("Terms_RightsTitle", resourceCulture);
            }
        }
        
        public static string Terms_RightsBody {
            get {
                return ResourceManager.GetString("Terms_RightsBody", resourceCulture);
            }
        }
        
        public static string Terms_WarrantiesTitle {
            get {
                return ResourceManager.GetString("Terms_WarrantiesTitle", resourceCulture);
            }
        }
        
        public static string Terms_WarrantiesBody {
            get {
                return ResourceManager.GetString("Terms_WarrantiesBody", resourceCulture);
            }
        }
        
        public static string Terms_IndeminityTitle {
            get {
                return ResourceManager.GetString("Terms_IndeminityTitle", resourceCulture);
            }
        }
        
        public static string Terms_IndemnityBody {
            get {
                return ResourceManager.GetString("Terms_IndemnityBody", resourceCulture);
            }
        }
        
        public static string Terms_JurisdictionTitle {
            get {
                return ResourceManager.GetString("Terms_JurisdictionTitle", resourceCulture);
            }
        }
        
        public static string Terms_JurisdictionBody {
            get {
                return ResourceManager.GetString("Terms_JurisdictionBody", resourceCulture);
            }
        }
        
        public static string Terms_SeverabilityTitle {
            get {
                return ResourceManager.GetString("Terms_SeverabilityTitle", resourceCulture);
            }
        }
        
        public static string Terms_SeverabilityBody {
            get {
                return ResourceManager.GetString("Terms_SeverabilityBody", resourceCulture);
            }
        }
        
        public static string Terms_WaiverTitle {
            get {
                return ResourceManager.GetString("Terms_WaiverTitle", resourceCulture);
            }
        }
        
        public static string Terms_WaiverBody {
            get {
                return ResourceManager.GetString("Terms_WaiverBody", resourceCulture);
            }
        }
        
        public static string Terms_NoticesTitle {
            get {
                return ResourceManager.GetString("Terms_NoticesTitle", resourceCulture);
            }
        }
        
        public static string Terms_NoticesBody {
            get {
                return ResourceManager.GetString("Terms_NoticesBody", resourceCulture);
            }
        }
        
        public static string Terms_ContactTitle {
            get {
                return ResourceManager.GetString("Terms_ContactTitle", resourceCulture);
            }
        }
        
        public static string Terms_ContactBody {
            get {
                return ResourceManager.GetString("Terms_ContactBody", resourceCulture);
            }
        }
        
        public static string Main_help {
            get {
                return ResourceManager.GetString("Main_help", resourceCulture);
            }
        }
        
        public static string Gallery_needPerms {
            get {
                return ResourceManager.GetString("Gallery_needPerms", resourceCulture);
            }
        }
        
        public static string PhotoEdit_AddedToQueue {
            get {
                return ResourceManager.GetString("PhotoEdit_AddedToQueue", resourceCulture);
            }
        }
        
        public static string PhotoEdit_QueueOrUpload_message {
            get {
                return ResourceManager.GetString("PhotoEdit_QueueOrUpload_message", resourceCulture);
            }
        }
        
        public static string PhotoEdit_QueueOrUpload_now {
            get {
                return ResourceManager.GetString("PhotoEdit_QueueOrUpload_now", resourceCulture);
            }
        }
        
        public static string PhotoEdit_QueueOrUpload_queue {
            get {
                return ResourceManager.GetString("PhotoEdit_QueueOrUpload_queue", resourceCulture);
            }
        }
        
        public static string PhotoEdit_QueueOrUpload_title {
            get {
                return ResourceManager.GetString("PhotoEdit_QueueOrUpload_title", resourceCulture);
            }
        }
        
        public static string Uploads_allBtn {
            get {
                return ResourceManager.GetString("Uploads_allBtn", resourceCulture);
            }
        }
        
        public static string Uploads_btn {
            get {
                return ResourceManager.GetString("Uploads_btn", resourceCulture);
            }
        }
        
        public static string Uploads_dataWarning {
            get {
                return ResourceManager.GetString("Uploads_dataWarning", resourceCulture);
            }
        }
        
        public static string Uploads_dataWarningContinue {
            get {
                return ResourceManager.GetString("Uploads_dataWarningContinue", resourceCulture);
            }
        }
        
        public static string Uploads_noneMessage {
            get {
                return ResourceManager.GetString("Uploads_noneMessage", resourceCulture);
            }
        }
        
        public static string Uploads_noneTitle {
            get {
                return ResourceManager.GetString("Uploads_noneTitle", resourceCulture);
            }
        }
        
        public static string Uploads_title {
            get {
                return ResourceManager.GetString("Uploads_title", resourceCulture);
            }
        }
        
        public static string Uploads_upSelectionBtn {
            get {
                return ResourceManager.GetString("Uploads_upSelectionBtn", resourceCulture);
            }
        }
        
        public static string Camera_holdStill {
            get {
                return ResourceManager.GetString("Camera_holdStill", resourceCulture);
            }
        }
        
        public static string Camera_noAccess {
            get {
                return ResourceManager.GetString("Camera_noAccess", resourceCulture);
            }
        }
        
        public static string Camera_overlayErr {
            get {
                return ResourceManager.GetString("Camera_overlayErr", resourceCulture);
            }
        }
        
        public static string Camera_permissionMessage {
            get {
                return ResourceManager.GetString("Camera_permissionMessage", resourceCulture);
            }
        }
        
        public static string Camera_permissionNeeded {
            get {
                return ResourceManager.GetString("Camera_permissionNeeded", resourceCulture);
            }
        }
        
        public static string OfflineModeWarning {
            get {
                return ResourceManager.GetString("OfflineModeWarning", resourceCulture);
            }
        }
        
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        public static string PhotoCell_btnDeselect {
            get {
                return ResourceManager.GetString("PhotoCell_btnDeselect", resourceCulture);
            }
        }
        
        public static string PhotoCell_btnSelect {
            get {
                return ResourceManager.GetString("PhotoCell_btnSelect", resourceCulture);
            }
        }
        
        public static string UploadCell_btnDeselect {
            get {
                return ResourceManager.GetString("UploadCell_btnDeselect", resourceCulture);
            }
        }
        
        public static string UploadCell_btnSelect {
            get {
                return ResourceManager.GetString("UploadCell_btnSelect", resourceCulture);
            }
        }
        
        public static string Trans_BodyPartsSkinRegions {
            get {
                return ResourceManager.GetString("Trans_BodyPartsSkinRegions", resourceCulture);
            }
        }
        
        public static string ContactList_title {
            get {
                return ResourceManager.GetString("ContactList_title", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_confirmRevokeMessage {
            get {
                return ResourceManager.GetString("ManageSharesPage_confirmRevokeMessage", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_noShares {
            get {
                return ResourceManager.GetString("ManageSharesPage_noShares", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_serverGetError {
            get {
                return ResourceManager.GetString("ManageSharesPage_serverGetError", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_title {
            get {
                return ResourceManager.GetString("ManageSharesPage_title", resourceCulture);
            }
        }
        
        public static string NewSharePage_contactBtn {
            get {
                return ResourceManager.GetString("NewSharePage_contactBtn", resourceCulture);
            }
        }
        
        public static string NewSharePage_emailPrompt {
            get {
                return ResourceManager.GetString("NewSharePage_emailPrompt", resourceCulture);
            }
        }
        
        public static string NewSharePage_error {
            get {
                return ResourceManager.GetString("NewSharePage_error", resourceCulture);
            }
        }
        
        public static string NewSharePage_finishBtn {
            get {
                return ResourceManager.GetString("NewSharePage_finishBtn", resourceCulture);
            }
        }
        
        public static string NewSharePage_header {
            get {
                return ResourceManager.GetString("NewSharePage_header", resourceCulture);
            }
        }
        
        public static string NewSharePage_revokeReminder {
            get {
                return ResourceManager.GetString("NewSharePage_revokeReminder", resourceCulture);
            }
        }
        
        public static string NewSharePage_success {
            get {
                return ResourceManager.GetString("NewSharePage_success", resourceCulture);
            }
        }
        
        public static string NewSharePage_timePicker {
            get {
                return ResourceManager.GetString("NewSharePage_timePicker", resourceCulture);
            }
        }
        
        public static string NewSharePage_timePrompt {
            get {
                return ResourceManager.GetString("NewSharePage_timePrompt", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_1Month {
            get {
                return ResourceManager.GetString("NewSharePage_time_1Month", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_1Week {
            get {
                return ResourceManager.GetString("NewSharePage_time_1Week", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_1Year {
            get {
                return ResourceManager.GetString("NewSharePage_time_1Year", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_2Weeks {
            get {
                return ResourceManager.GetString("NewSharePage_time_2Weeks", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_6Months {
            get {
                return ResourceManager.GetString("NewSharePage_time_6Months", resourceCulture);
            }
        }
        
        public static string NewSharePage_time_forever {
            get {
                return ResourceManager.GetString("NewSharePage_time_forever", resourceCulture);
            }
        }
        
        public static string NewSharePage_title {
            get {
                return ResourceManager.GetString("NewSharePage_title", resourceCulture);
            }
        }
        
        public static string Main_manageShares {
            get {
                return ResourceManager.GetString("Main_manageShares", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_deleteConfirm {
            get {
                return ResourceManager.GetString("ManageSharesPage_deleteConfirm", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_deleteErr {
            get {
                return ResourceManager.GetString("ManageSharesPage_deleteErr", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_deleteSuccess {
            get {
                return ResourceManager.GetString("ManageSharesPage_deleteSuccess", resourceCulture);
            }
        }
        
        public static string ManageSharesPage_deleteTitle {
            get {
                return ResourceManager.GetString("ManageSharesPage_deleteTitle", resourceCulture);
            }
        }
        
        public static string NewSharePage_successTitle {
            get {
                return ResourceManager.GetString("NewSharePage_successTitle", resourceCulture);
            }
        }
        
        public static string Main_manageStudies {
            get {
                return ResourceManager.GetString("Main_manageStudies", resourceCulture);
            }
        }
        
        public static string NewSharePage_studyButton {
            get {
                return ResourceManager.GetString("NewSharePage_studyButton", resourceCulture);
            }
        }
        
        public static string StudyListPage_codeInvalid {
            get {
                return ResourceManager.GetString("StudyListPage_codeInvalid", resourceCulture);
            }
        }
        
        public static string StudyListPage_codeMessage {
            get {
                return ResourceManager.GetString("StudyListPage_codeMessage", resourceCulture);
            }
        }
        
        public static string StudyListPage_codeSuccess {
            get {
                return ResourceManager.GetString("StudyListPage_codeSuccess", resourceCulture);
            }
        }
        
        public static string StudyListPage_codeTitle {
            get {
                return ResourceManager.GetString("StudyListPage_codeTitle", resourceCulture);
            }
        }
        
        public static string StudyListPage_connectionErr {
            get {
                return ResourceManager.GetString("StudyListPage_connectionErr", resourceCulture);
            }
        }
        
        public static string StudyListPage_deleteConfirmBtn {
            get {
                return ResourceManager.GetString("StudyListPage_deleteConfirmBtn", resourceCulture);
            }
        }
        
        public static string StudyListPage_deleteConfirmMessage {
            get {
                return ResourceManager.GetString("StudyListPage_deleteConfirmMessage", resourceCulture);
            }
        }
        
        public static string StudyListPage_deleteConfirmTitle {
            get {
                return ResourceManager.GetString("StudyListPage_deleteConfirmTitle", resourceCulture);
            }
        }
        
        public static string StudyListPage_deleteErr {
            get {
                return ResourceManager.GetString("StudyListPage_deleteErr", resourceCulture);
            }
        }
        
        public static string StudyListPage_deleteSuccess {
            get {
                return ResourceManager.GetString("StudyListPage_deleteSuccess", resourceCulture);
            }
        }
        
        public static string StudyListPage_join {
            get {
                return ResourceManager.GetString("StudyListPage_join", resourceCulture);
            }
        }
        
        public static string StudyListPage_noStudies {
            get {
                return ResourceManager.GetString("StudyListPage_noStudies", resourceCulture);
            }
        }
        
        public static string StudyListPage_title {
            get {
                return ResourceManager.GetString("StudyListPage_title", resourceCulture);
            }
        }
    }
}
